site_name: 'Systems Thinking in the Age of AI'
site_description: 'This is an intelligent textbook has many interactive resources for teaching systems thinking to a wide audience from high school students to business executives.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/systems-thinking/'
repo_url: 'https://github.com/dmccreary/systems-thinking'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About this Website: about.md
  - Table of Contents: table-of-contents.md
  - Part 1 Introduction:
    - Introduction: intro/index.md
    - Forward: intro/forward.md
    - Preface: intro/preface.md
    - Acknowledgements: intro/acknowledgements.md
    - About the Author: intro/about-the-authors.md
    - Ch 1 Introduction: intro/ch-01-intro.md
    - Ch 2 Graphs: intro/ch-02-graph.md
    - Ch 3 Systems Thinking: intro/ch-03-systems.md
    - Ch 4 Graph Systems Thinking: intro/ch-04-systems-graph.md
    - Ch 5 Emergence: intro/ch-05-emergence.md
    - Ch 6 Complex Adaptive Systems: intro/ch-06-cas.md

  - Part 2 Archetypes:
    - Introduction: archetypes/index.md

    - Tragedy of the Commons: 
      - Intro: archetypes/tragedy-of-the-commons/index.md
      - Classic Story: archetypes/tragedy-of-the-commons/classic-toc.md
    - Introduction to Archetypes: archetypes/intro-archetypes.md
    - Tragedy of the Commons: archetypes/commons.md
    - Alternative Tragedy of Commons: archetypes/tragedy-of-the-commons.md
    - The AI Flywheel: archetypes/success-to-the-successful/ai-flywheel/index.md
    - Concept Standards: archetypes/concept-standards.md
    - Search and Reuse: archetypes/search-and-reuse.md

    - Fixes that Fail:
      - Introduction: archetypes/fixes-that-fail/index.md
      - Banning AI: archetypes/fixes-that-fail/banning-ai/index.md
      - Banning Books:
          - Introduction: archetypes/fixes-that-fail/banning-books/index.md
          - Causal Diagram: archetypes/fixes-that-fail/banning-books/cld-generation.md
      - Cutting Coding: archetypes/fixes-that-fail/cutting-coding/index.md
      - Cutting STEM: archetypes/fixes-that-fail/cutting-stem/index.md
      - Cutting AI Training: 
          - Introduction: archetypes/fixes-that-fail/cutting-ai-training/index.md
          - Causal Diagram: archetypes/fixes-that-fail/cutting-ai-training/cld-generation.md
      - Grade Inflation: archetypes/fixes-that-fail/grade-inflation/index.md
      - Layoffs: archetypes/fixes-that-fail/layoffs/index.md
      - Open Offices: archetypes/fixes-that-fail/open-offices/index.md
      - Painkillers: archetypes/fixes-that-fail/painkillers/index.md
      - Return to Office: archetypes/fixes-that-fail/return-to-office/index.md
      - Security Theater: archetypes/fixes-that-fail/security-theater/index.md
      - Teach to Test: archetypes/fixes-that-fail/teach-to-the-test/index.md
      - Traffic Congestion: archetypes/fixes-that-fail/traffic-congestion/index.md
      - Zero Tolerance: archetypes/fixes-that-fail/zero-tolerance/index.md
    
    - Limits to Growth:
      - Introduction: archetypes/limits-to-growth/index.md
      - Antibiotic Effectiveness: archetypes/limits-to-growth/antibiotic-effectiveness/index.md
      - Bacteria Growth: archetypes/limits-to-growth/bacteria/index.md
      - Business Expansion: archetypes/limits-to-growth/business-expansion/index.md
      - Gaming Skills: archetypes/limits-to-growth/gaming-skills/index.md
      - Humans on Earth: archetypes/limits-to-growth/humans-on-earth/index.md
      - Intensive Agriculture: archetypes/limits-to-growth/intensive-agriculture/index.md
      - LLMs: archetypes/limits-to-growth/llms/index.md
      - Moore's Law: archetypes/limits-to-growth/moores-law/index.md
      - Social Media: archetypes/limits-to-growth/social-media/index.md
      - Steam Engines: archetypes/limits-to-growth/steam-engines/index.md
      - Student Activity Overcommitment: archetypes/limits-to-growth/student-activity-overcommittment/index.md

    - Success to the Successful:
      - Introduction:        archetypes/success-to-the-successful/index.md
      - AI Flywheel:         archetypes/success-to-the-successful/ai-flywheel/index.md
      - Educational Funding: 
        - Introduction: archetypes/success-to-the-successful/educational-funding/index.md
        - CLD Test Results: archetypes/success-to-the-successful/educational-funding/cld-test-results.md
      - Healthcare Access:   archetypes/success-to-the-successful/healthcare-access/index.md
      - Research Funding:    archetypes/success-to-the-successful/research-funding/index.md
      - Social Media:        archetypes/success-to-the-successful/social-media/index.md
      - Sports Development:  archetypes/success-to-the-successful/sports-development/index.md
      - Technology Platform: archetypes/success-to-the-successful/technology-platform/index.md
      - Venture Capital:     archetypes/success-to-the-successful/venture-capital/index.md
      - Wealth Inequality:   archetypes/success-to-the-successful/wealth-inequality/index.md
      # - College Rankings: archetypes/success-to-the-successful/college-rankings.md
      # - Political Polarization: archetypes/success-to-the-successful/political-polarization.md

  # - Render Tests:
  #  - render-tests/mermaid-test.md
  #  - render-tests/state-diagram.md
  #  - render-tests/influence-diagram.md
  #  - Chapter X: concepts/graph.md
  #  - Chapter X+1: concepts/graph.md
  #- Pt 3 Case Studies:
  # - Part 3 Case Studies:
  #   - Chapter 9: case-studies/healthcare.md
  - Causal Loop Diagrams:
    - Introduction: clds/index.md
    - Bank Balance: clds/bank-balance/index.md
    - Theromstat: clds/thermostat/index.md
 
  
  - Increasing Maturity:
    - Introduction: cmm-strategies/index.md
    - Microstrategies: cmm-strategies/microstrategies.md
    - Silo Busting Microstrategies: cmm-strategies/silo-busting-microstrategies.md
  
  - MicroSims:
    - Introduction: sims/index.md
    - High School Simulations: sims/high-school.md
    - Tragedy of the Commons: sims/toc/index.md
    - Moore's Law: sims/moores-law/index.md
    - Agent CLD: sims/agent-cld/index.md
    - CMM Simulation: sims/cmm/index.md
    - CLD Viewer: sims/cld-viewer/index.md
    - Template: sims/template/index.md
  
  - Stories:
    - Introduction: stories/index.md
    - Tragedy of the Commons: stories/tragedy-of-the-commons/index.md
    - Moore's Law: stories/moores-law/index.md
  - Prompts:
    - Knowledge Graphs:
      - Concept Enumeration: prompts/knowledge-graphs/concept-enumeration.md
      - Concept Dependency: prompts/knowledge-graphs/concept-dependency.md
      - Concept Taxonomy: prompts/knowledge-graphs/concept-taxonomy.md
      - Graph Demo: prompts/knowledge-graphs/graph/index.md
    - Enumerating Archetypes: prompts/enumerating-archetypes.md
    - Causal Loop Diagram: prompts/cld/index.md
    - Archetype Examples:
      - Introduction: prompts/archetype-examples/index.md
      - Fixes that Fail: prompts/archetype-examples/fixes-that-fail.md
  - Archetypes: archetypes.md
  - Presentations: slides.md
  - Glossary: glossary.md
  - What They Are Saying: what-they-are-saying.md
  - Colophon: colophon.md
  - References: references.md
  - License: license.md
  - Contact: contact.md

edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/new-logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - meta
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.tabbed
# enable LaTeX equation rendering
#  - pymdownx.arithmatex:
#      generic: true
extra_css:
   - css/extra.css
extra_javascript:
    - js/extra.js
    # needed for mathjax to work
    # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - social
  - social_override
extra:
    analytics:
      provider: google
      # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
      property: G-ZQMDCX1BVL
